/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/healthz': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health check
		 * @description Responds with "PONG!" if the service is healthy.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful response */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': string;
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/oauth/providers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List available OAuth providers
		 * @description Returns a list of configured OAuth provider names that can be used for login.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of provider names. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Providers'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/oauth/{provider}/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Initiate OAuth Login
		 * @description Starts the OAuth 2.0 Authorization Code flow by redirecting the user to the specified provider's login page.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The name of the OAuth provider (e.g., "pocketid"). */
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Temporary Redirect to the OAuth provider's authorization URL. */
				307: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/oauth/{provider}/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * OAuth Callback
		 * @description Handles the callback from the OAuth provider after the user has authenticated. The server exchanges the code for a token, creates a session, and sets session cookies.
		 */
		get: {
			parameters: {
				query: {
					/** @description The authorization code provided by the OAuth server. */
					code: string;
					/** @description The state parameter for CSRF protection. */
					state: string;
				};
				header?: never;
				path: {
					/** @description The name of the OAuth provider. */
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description See Other. Redirects to the application's root on successful login. */
				303: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request, e.g., invalid state or code. */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Current User
		 * @description Retrieves the session information for the currently authenticated user. Requires a valid session cookie.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The current user and session information. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UserSession'];
					};
				};
				/** @description Unauthorized. The user is not authenticated. */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/sign-out': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign Out
		 * @description Invalidates the user's session and clears authentication cookies.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successfully signed out. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/buckets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List buckets
		 * @description Fetches all buckets
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of buckets */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Bucket'][];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a new bucket
		 * @description Creates a new S3 bucket.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						name?: string;
					};
				};
			};
			responses: {
				/** @description Bucket created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Invalid bucket name */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List objects
		 * @description Fetches all objects in a folder
		 */
		get: {
			parameters: {
				query?: {
					folder?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of objects */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ObjectList'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Get a presigned URL for upload
		 * @description Gets a presigned URL that can be used to upload a file.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['UploadBody'];
				};
			};
			responses: {
				/** @description A presigned URL for upload */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UploadResult'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/categories': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List categories
		 * @description Fetches all categories that can be used
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of categories */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['CategoriesList'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/item': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get an object
		 * @description Gets a single object from storage.
		 */
		get: {
			parameters: {
				query: {
					/** @description The full key of the object to delete. */
					item: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Object retrieved successfully. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ObjectItem'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Delete an object
		 * @description Deletes a single object from storage.
		 */
		delete: {
			parameters: {
				query: {
					/** @description The full key of the object to delete. */
					item: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Object deleted successfully. */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/folder': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a folder
		 * @description Creates a new folder in the storage.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						name: string;
					};
				};
			};
			responses: {
				/** @description Folder created successfully. */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		/**
		 * Delete a folder
		 * @description Deletes a folder and all of its contents.
		 */
		delete: {
			parameters: {
				query: {
					/** @description The full path of the folder to delete. */
					path: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Folder deleted successfully. */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/recent': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List recent objects
		 * @description Fetches the most recently modified objects.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of recent objects. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ObjectList'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/category/{category}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List objects by category
		 * @description Fetches all objects belonging to a specific category.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The category to filter by (e.g., images, documents, music, code). */
					category: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A list of objects in the specified category. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ObjectList'];
					};
				};
				/** @description Invalid category specified. */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/storage/objects/url': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a presigned URL
		 * @description Gets a presigned URL for an item
		 */
		get: {
			parameters: {
				query: {
					item: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description A presigned URL */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': string;
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/p': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Proxy to an S3 object
		 * @description Redirects to a presigned URL for a given object, hiding the direct storage URL.
		 */
		get: {
			parameters: {
				query: {
					url: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Temporary Redirect to the presigned URL. */
				307: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		/**
		 * Upload an S3 object
		 * @description Redirects to a presigned URL for a given object, hiding the direct storage URL.
		 */
		put: {
			parameters: {
				query: {
					url: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Temporary Redirect to the presigned URL. */
				307: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['Error'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		User: {
			/** Format: uuid */
			id: string;
			name: string;
			/** Format: email */
			email: string;
			image?: string | null;
		};
		/** @example [
		 *       "pocketid",
		 *       "google"
		 *     ] */
		Providers: string[];
		Session: {
			/** Format: uuid */
			id?: string;
			/** Format: date-time */
			expiresAt?: string;
		};
		UserSession: {
			user: components['schemas']['User'];
			session: components['schemas']['Session'];
		};
		Bucket: {
			name: string;
			/** Format: date-time */
			creationDate: string;
		};
		ObjectItem: {
			key: string;
			/** Format: date-time */
			lastModified?: string;
			eTag?: string;
			size?: number;
			storageClass?: string;
			contentType?: string;
			metadata?: {
				[key: string]: string;
			};
		};
		/** @example [
		 *       "documents",
		 *       "music",
		 *       "images"
		 *     ] */
		CategoriesList: string[];
		ObjectList: {
			count: number;
			list: components['schemas']['ObjectItem'][];
		};
		Error: {
			error?: string;
		};
		UploadBody: {
			key: string;
			type: string;
			folder?: string;
			metadata?: {
				[key: string]: string;
			};
		};
		UploadResult: {
			presignedUrl: string;
			finalName: string;
			metadata?: {
				[key: string]: string;
			};
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
