services:
  app:
    image: git.ombrage.space/salokain/opendrive/app:${TAG-latest}
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - 3000
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000/api/v1/ping']
      retries: 5
      timeout: 3s
      interval: 10s
      start_period: 2s
    environment:
      - LOG_LEVEL=${LOG_LEVEL-debug}
      - DATABASE_URL=postgres://${POSTGRES_USER-postgres}:${POSTGRES_PASSWORD-postgres}@db:5432/${POSTGRES_DB-opendrive}
      - ORIGIN=https://drive.ombrage.space
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - BETTER_AUTH_URL=https://drive.ombrage.space
      - MINIO_ENDPOINT=minio
    networks:
      - proxy
      - opendrive
    labels:
      - traefik.enable=true
      - traefik.http.routers.opendrive-app.rule=Host(`drive.ombrage.space`)
      - traefik.http.routers.opendrive-app.entrypoints=websecure
      - traefik.http.routers.opendrive-app.tls.certResolver=letsencrypt
      - traefik.http.routers.opendrive-app.middlewares=traefik-forward-auth
      - traefik.http.services.opendrive-app.loadbalancer.server.port=3000
      - homepage.group=Media
      - homepage.name=Opendrive
      - homepage.icon=nextcloud.svg
      - homepage.href=https://drive.ombrage.space
      - homepage.description=Storatge management

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    networks:
      - opendrive
    environment:
      - MINIO_ROOT_USER=opendrive
      - MINIO_ROOT_PASSWORD=opendrive
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:9000/minio/health/live']
      retries: 5
      timeout: 3s
      interval: 10s
      start_period: 2s
    ports:
      - 9000
    command: server /data
    volumes:
      - minio_data:/data

  db:
    image: postgres:17
    restart: unless-stopped
    networks:
      - opendrive
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_DB=${POSTGRES_DB-opendrive}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER-postgres} -d ${POSTGRES_DB-opendrive}'"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  proxy:
    external: true
  opendrive:
    external: false
