services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      storage:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test:
        [CMD, wget, --quiet, --timeout=3, --tries=1, --spider, http://0.0.0.0:8080/api/v1/healthz]
      retries: 5
      timeout: 3s
      interval: 10s
      start_period: 2s
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER-postgres}:${POSTGRES_PASSWORD-postgres}@db:5432/${POSTGRES_DB-opendrive}?sslmode=disable
      - ORIGIN=http://0.0.0.0:8080
      - STORAGE_URL=http://storage:9000
      - BODY_SIZE_LIMIT=Infinity
      - OAUTH_PROVIDERS=${OAUTH_PROVIDERS}
      - OAUTH_POCKETID_DISCOVERY_URL=${OAUTH_POCKETID_DISCOVERY_URL}
      - OAUTH_POCKETID_REDIRECT_URL=${OAUTH_POCKETID_REDIRECT_URL}
      - OAUTH_POCKETID_CLIENT_ID=${OAUTH_POCKETID_CLIENT_ID}
      - OAUTH_POCKETID_CLIENT_SECRET=${OAUTH_POCKETID_CLIENT_SECRET}

  storage:
    image: git.ombrage.space/opendrive/storage:latest
    restart: unless-stopped
    healthcheck:
      test: [CMD, curl, -f, http://0.0.0.0:9000/minio/health/live]
      retries: 5
      timeout: 3s
      interval: 10s
      start_period: 2s
    environment:
      - MINIO_ROOT_USER=opendrive
      - MINIO_ROOT_PASSWORD=opendrive
    ports:
      - 9000
    volumes:
      - storage_data:/data

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_DB=${POSTGRES_DB-opendrive}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER-postgres} -d ${POSTGRES_DB-opendrive}'"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

volumes:
  postgres_data:
    driver: local
  storage_data:
    driver: local
