services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - storage:/data/storage
      - db:/data/db
    env_file: .env
    environment:
      - LOG_LEVEL=debug
      - STORAGE_PATH=/data/storage
      - SIMPLE_MODE=true
      - ORIGIN=http://localhost:8080

volumes:
  db: {}
  storage: {}
