// Package services provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package services

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Bucket defines model for Bucket.
type Bucket struct {
	CreationDate time.Time `json:"creationDate"`
	Name         string    `json:"name"`
}

// CategoriesList defines model for CategoriesList.
type CategoriesList = []string

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// ObjectItem defines model for ObjectItem.
type ObjectItem struct {
	ContentType  *string            `json:"contentType,omitempty"`
	ETag         *string            `json:"eTag,omitempty"`
	Key          string             `json:"key"`
	LastModified *time.Time         `json:"lastModified,omitempty"`
	Metadata     *map[string]string `json:"metadata,omitempty"`
	Size         *int               `json:"size,omitempty"`
	StorageClass *string            `json:"storageClass,omitempty"`
}

// ObjectList defines model for ObjectList.
type ObjectList struct {
	Count int          `json:"count"`
	List  []ObjectItem `json:"list"`
}

// Providers defines model for Providers.
type Providers = []string

// Session defines model for Session.
type Session struct {
	ExpiresAt *time.Time          `json:"expiresAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
}

// UploadBody defines model for UploadBody.
type UploadBody struct {
	Folder   *string            `json:"folder,omitempty"`
	Key      string             `json:"key"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	Type     string             `json:"type"`
}

// UploadResult defines model for UploadResult.
type UploadResult struct {
	FinalName    string             `json:"finalName"`
	Metadata     *map[string]string `json:"metadata,omitempty"`
	PresignedUrl string             `json:"presignedUrl"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Image *string             `json:"image"`
	Name  string              `json:"name"`
}

// UserSession defines model for UserSession.
type UserSession struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

// GetApiV1AuthOauthProviderCallbackParams defines parameters for GetApiV1AuthOauthProviderCallback.
type GetApiV1AuthOauthProviderCallbackParams struct {
	// Code The authorization code provided by the OAuth server.
	Code string `form:"code" json:"code"`

	// State The state parameter for CSRF protection.
	State string `form:"state" json:"state"`
}

// PostApiV1StorageBucketsJSONBody defines parameters for PostApiV1StorageBuckets.
type PostApiV1StorageBucketsJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// GetApiV1StorageObjectsParams defines parameters for GetApiV1StorageObjects.
type GetApiV1StorageObjectsParams struct {
	Folder *string `form:"folder,omitempty" json:"folder,omitempty"`
}

// DeleteApiV1StorageObjectsFolderParams defines parameters for DeleteApiV1StorageObjectsFolder.
type DeleteApiV1StorageObjectsFolderParams struct {
	// Path The full path of the folder to delete.
	Path string `form:"path" json:"path"`
}

// PostApiV1StorageObjectsFolderJSONBody defines parameters for PostApiV1StorageObjectsFolder.
type PostApiV1StorageObjectsFolderJSONBody struct {
	Name string `json:"name"`
}

// DeleteApiV1StorageObjectsItemParams defines parameters for DeleteApiV1StorageObjectsItem.
type DeleteApiV1StorageObjectsItemParams struct {
	// Item The full key of the object to delete.
	Item string `form:"item" json:"item"`
}

// GetApiV1StorageObjectsItemParams defines parameters for GetApiV1StorageObjectsItem.
type GetApiV1StorageObjectsItemParams struct {
	// Item The full key of the object to delete.
	Item string `form:"item" json:"item"`
}

// GetApiV1StorageObjectsUrlParams defines parameters for GetApiV1StorageObjectsUrl.
type GetApiV1StorageObjectsUrlParams struct {
	Item string `form:"item" json:"item"`
}

// GetPBucketParams defines parameters for GetPBucket.
type GetPBucketParams struct {
	Item string `form:"item" json:"item"`
}

// PostApiV1StorageBucketsJSONRequestBody defines body for PostApiV1StorageBuckets for application/json ContentType.
type PostApiV1StorageBucketsJSONRequestBody PostApiV1StorageBucketsJSONBody

// PostApiV1StorageObjectsJSONRequestBody defines body for PostApiV1StorageObjects for application/json ContentType.
type PostApiV1StorageObjectsJSONRequestBody = UploadBody

// PostApiV1StorageObjectsFolderJSONRequestBody defines body for PostApiV1StorageObjectsFolder for application/json ContentType.
type PostApiV1StorageObjectsFolderJSONRequestBody PostApiV1StorageObjectsFolderJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Current User
	// (GET /api/v1/auth/me)
	GetApiV1AuthMe(w http.ResponseWriter, r *http.Request)
	// List available OAuth providers
	// (GET /api/v1/auth/oauth/providers)
	GetApiV1AuthOauthProviders(w http.ResponseWriter, r *http.Request)
	// OAuth Callback
	// (GET /api/v1/auth/oauth/{provider}/callback)
	GetApiV1AuthOauthProviderCallback(w http.ResponseWriter, r *http.Request, provider string, params GetApiV1AuthOauthProviderCallbackParams)
	// Initiate OAuth Login
	// (GET /api/v1/auth/oauth/{provider}/login)
	GetApiV1AuthOauthProviderLogin(w http.ResponseWriter, r *http.Request, provider string)
	// Sign Out
	// (POST /api/v1/auth/sign-out)
	PostApiV1AuthSignOut(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /api/v1/healthz)
	GetApiV1Healthz(w http.ResponseWriter, r *http.Request)
	// List buckets
	// (GET /api/v1/storage/buckets)
	GetApiV1StorageBuckets(w http.ResponseWriter, r *http.Request)
	// Create a new bucket
	// (POST /api/v1/storage/buckets)
	PostApiV1StorageBuckets(w http.ResponseWriter, r *http.Request)
	// List objects
	// (GET /api/v1/storage/objects)
	GetApiV1StorageObjects(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsParams)
	// Get a presigned URL for upload
	// (POST /api/v1/storage/objects)
	PostApiV1StorageObjects(w http.ResponseWriter, r *http.Request)
	// List categories
	// (GET /api/v1/storage/objects/categories)
	GetApiV1StorageObjectsCategories(w http.ResponseWriter, r *http.Request)
	// List objects by category
	// (GET /api/v1/storage/objects/category/{category})
	GetApiV1StorageObjectsCategoryCategory(w http.ResponseWriter, r *http.Request, category string)
	// Delete a folder
	// (DELETE /api/v1/storage/objects/folder)
	DeleteApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request, params DeleteApiV1StorageObjectsFolderParams)
	// Create a folder
	// (POST /api/v1/storage/objects/folder)
	PostApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request)
	// Delete an object
	// (DELETE /api/v1/storage/objects/item)
	DeleteApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request, params DeleteApiV1StorageObjectsItemParams)
	// Get an object
	// (GET /api/v1/storage/objects/item)
	GetApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsItemParams)
	// List recent objects
	// (GET /api/v1/storage/objects/recent)
	GetApiV1StorageObjectsRecent(w http.ResponseWriter, r *http.Request)
	// Get a presigned URL
	// (GET /api/v1/storage/objects/url)
	GetApiV1StorageObjectsUrl(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsUrlParams)
	// Proxy to an S3 object
	// (GET /p/{bucket})
	GetPBucket(w http.ResponseWriter, r *http.Request, bucket string, params GetPBucketParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Current User
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetApiV1AuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available OAuth providers
// (GET /api/v1/auth/oauth/providers)
func (_ Unimplemented) GetApiV1AuthOauthProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OAuth Callback
// (GET /api/v1/auth/oauth/{provider}/callback)
func (_ Unimplemented) GetApiV1AuthOauthProviderCallback(w http.ResponseWriter, r *http.Request, provider string, params GetApiV1AuthOauthProviderCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate OAuth Login
// (GET /api/v1/auth/oauth/{provider}/login)
func (_ Unimplemented) GetApiV1AuthOauthProviderLogin(w http.ResponseWriter, r *http.Request, provider string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sign Out
// (POST /api/v1/auth/sign-out)
func (_ Unimplemented) PostApiV1AuthSignOut(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /api/v1/healthz)
func (_ Unimplemented) GetApiV1Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List buckets
// (GET /api/v1/storage/buckets)
func (_ Unimplemented) GetApiV1StorageBuckets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new bucket
// (POST /api/v1/storage/buckets)
func (_ Unimplemented) PostApiV1StorageBuckets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List objects
// (GET /api/v1/storage/objects)
func (_ Unimplemented) GetApiV1StorageObjects(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a presigned URL for upload
// (POST /api/v1/storage/objects)
func (_ Unimplemented) PostApiV1StorageObjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List categories
// (GET /api/v1/storage/objects/categories)
func (_ Unimplemented) GetApiV1StorageObjectsCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List objects by category
// (GET /api/v1/storage/objects/category/{category})
func (_ Unimplemented) GetApiV1StorageObjectsCategoryCategory(w http.ResponseWriter, r *http.Request, category string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a folder
// (DELETE /api/v1/storage/objects/folder)
func (_ Unimplemented) DeleteApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request, params DeleteApiV1StorageObjectsFolderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a folder
// (POST /api/v1/storage/objects/folder)
func (_ Unimplemented) PostApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an object
// (DELETE /api/v1/storage/objects/item)
func (_ Unimplemented) DeleteApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request, params DeleteApiV1StorageObjectsItemParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an object
// (GET /api/v1/storage/objects/item)
func (_ Unimplemented) GetApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsItemParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recent objects
// (GET /api/v1/storage/objects/recent)
func (_ Unimplemented) GetApiV1StorageObjectsRecent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a presigned URL
// (GET /api/v1/storage/objects/url)
func (_ Unimplemented) GetApiV1StorageObjectsUrl(w http.ResponseWriter, r *http.Request, params GetApiV1StorageObjectsUrlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Proxy to an S3 object
// (GET /p/{bucket})
func (_ Unimplemented) GetPBucket(w http.ResponseWriter, r *http.Request, bucket string, params GetPBucketParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1AuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AuthOauthProviders operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AuthOauthProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AuthOauthProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AuthOauthProviderCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AuthOauthProviderCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", chi.URLParam(r, "provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1AuthOauthProviderCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AuthOauthProviderCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AuthOauthProviderLogin operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AuthOauthProviderLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", chi.URLParam(r, "provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AuthOauthProviderLogin(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthSignOut operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthSignOut(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthSignOut(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Healthz operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageBuckets operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageBuckets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageBuckets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1StorageBuckets operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1StorageBuckets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1StorageBuckets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjects operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjects(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1StorageObjectsParams

	// ------------- Optional query parameter "folder" -------------

	err = runtime.BindQueryParameter("form", true, false, "folder", r.URL.Query(), &params.Folder)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "folder", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1StorageObjects operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1StorageObjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1StorageObjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjectsCategories operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjectsCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjectsCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjectsCategoryCategory operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjectsCategoryCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "category" -------------
	var category string

	err = runtime.BindStyledParameterWithOptions("simple", "category", chi.URLParam(r, "category"), &category, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjectsCategoryCategory(w, r, category)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1StorageObjectsFolder operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiV1StorageObjectsFolderParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1StorageObjectsFolder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1StorageObjectsFolder operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1StorageObjectsFolder(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1StorageObjectsFolder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1StorageObjectsItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiV1StorageObjectsItemParams

	// ------------- Required query parameter "item" -------------

	if paramValue := r.URL.Query().Get("item"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "item"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "item", r.URL.Query(), &params.Item)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1StorageObjectsItem(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjectsItem operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjectsItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1StorageObjectsItemParams

	// ------------- Required query parameter "item" -------------

	if paramValue := r.URL.Query().Get("item"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "item"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "item", r.URL.Query(), &params.Item)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjectsItem(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjectsRecent operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjectsRecent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjectsRecent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1StorageObjectsUrl operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1StorageObjectsUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1StorageObjectsUrlParams

	// ------------- Required query parameter "item" -------------

	if paramValue := r.URL.Query().Get("item"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "item"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "item", r.URL.Query(), &params.Item)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1StorageObjectsUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPBucket operation middleware
func (siw *ServerInterfaceWrapper) GetPBucket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bucket" -------------
	var bucket string

	err = runtime.BindStyledParameterWithOptions("simple", "bucket", chi.URLParam(r, "bucket"), &bucket, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPBucketParams

	// ------------- Required query parameter "item" -------------

	if paramValue := r.URL.Query().Get("item"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "item"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "item", r.URL.Query(), &params.Item)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPBucket(w, r, bucket, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetApiV1AuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/oauth/providers", wrapper.GetApiV1AuthOauthProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/oauth/{provider}/callback", wrapper.GetApiV1AuthOauthProviderCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/oauth/{provider}/login", wrapper.GetApiV1AuthOauthProviderLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/sign-out", wrapper.PostApiV1AuthSignOut)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/healthz", wrapper.GetApiV1Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/buckets", wrapper.GetApiV1StorageBuckets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/storage/buckets", wrapper.PostApiV1StorageBuckets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects", wrapper.GetApiV1StorageObjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/storage/objects", wrapper.PostApiV1StorageObjects)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects/categories", wrapper.GetApiV1StorageObjectsCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects/category/{category}", wrapper.GetApiV1StorageObjectsCategoryCategory)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/storage/objects/folder", wrapper.DeleteApiV1StorageObjectsFolder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/storage/objects/folder", wrapper.PostApiV1StorageObjectsFolder)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/storage/objects/item", wrapper.DeleteApiV1StorageObjectsItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects/item", wrapper.GetApiV1StorageObjectsItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects/recent", wrapper.GetApiV1StorageObjectsRecent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/storage/objects/url", wrapper.GetApiV1StorageObjectsUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/p/{bucket}", wrapper.GetPBucket)
	})

	return r
}
