#!/usr/bin/env bun
//MISE description="Render the feature graphics for the README, the docs and the Play Store"
// Renders the feature graphics: one each for the web app, the desktop app and
// the mobile app, plus the mobile one at the Play Store's 1024x500 and its
// phone screenshots.
//
//   mise run graphics
//
// Each is a page laid out here and photographed by Chromium, around the
// screenshots in docs/images/src. Those are taken from a running instance and
// are not regenerated by this script: docs/images/README.md says how each was
// made.
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { chromium } from "@playwright/test";

const root = join(import.meta.dir, "..", "..");
const src = join(root, "docs/images/src");
const out = join(root, "docs/images");
// Inlined: a page set from a string may not read files.
const image = async (name: string) =>
	`data:image/webp;base64,${Buffer.from(await Bun.file(join(src, name)).bytes()).toString("base64")}`;
const web = await image("web.webp");
const desktop = await image("desktop.webp");
const drive = await image("mobile-drive.webp");
const player = await image("mobile-player.webp");

// The dark bordeaux theme: `app.css`, as `Theme.kt` also spells it.
const GROUND = "#0c0b13";
const INK = "#f4eff5";
const MUTED = "#a99fb2";
const ACCENT = "#d8516a";
const GLOW = "#b94082";
const EMBER = "#d67d5e";
const FONT = `ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif`;

/** The logo's moon, drawn large: what sits behind every device. */
const moon = (id: string) => `
<svg viewBox="0 0 48 48" aria-hidden="true">
  <defs>
    <linearGradient id="l${id}" x1="0" y1="1" x2="1" y2="0">
      <stop offset="0" stop-color="${ACCENT}"/><stop offset="1" stop-color="${GLOW}"/>
    </linearGradient>
    <radialGradient id="s${id}" cx="31" cy="17" r="20" gradientUnits="userSpaceOnUse">
      <stop offset="0.72" stop-color="#000"/><stop offset="1" stop-color="#fff"/>
    </radialGradient>
    <mask id="e${id}"><rect width="48" height="48" fill="#fff"/><circle cx="31" cy="17" r="20" fill="url(#s${id})"/></mask>
  </defs>
  <circle cx="24" cy="24" r="21" fill="url(#l${id})" mask="url(#e${id})"/>
</svg>`;

interface Graphic {
	name: string;
	line: string;
	detail: string;
	/** What stands on the right, over the moon. */
	stage: string;
}

const phone = (shot: string, style: string) =>
	`<div class="phone" style="${style}"><img src="${shot}" alt=""></div>`;

const GRAPHICS: Graphic[] = [
	{
		name: "feature-web",
		line: "Your files, on your own server.",
		detail:
			"A drive for files, music, video and documents that you host yourself.",
		stage: `<div class="window browser" style="left: 470px; top: 96px; width: 760px;">
			<div class="bar"><i></i><i></i><i></i><span>files.example.com</span></div>
			<img src="${web}" alt="">
		</div>`,
	},
	{
		name: "feature-desktop",
		line: "Folders that stay in sync.",
		detail:
			"Penombre Sync keeps folders on your computer and your drive the same, both ways.",
		stage: `<div class="window app" style="left: 610px; top: 58px; width: 300px;">
			<div class="bar"><i></i><i></i><i></i></div>
			<img src="${desktop}" alt="">
		</div>`,
	},
	{
		name: "feature-mobile",
		line: "Your drive, in your pocket.",
		detail:
			"Browse, upload, watch and listen, from the server you already run.",
		stage:
			phone(player, "left: 760px; top: 96px; transform: rotate(7deg);") +
			phone(drive, "left: 560px; top: 46px; transform: rotate(-5deg);"),
	},
];

const page = (graphic: Graphic) => `<!doctype html>
<html><head><meta charset="utf-8"><style>
  * { box-sizing: border-box; margin: 0; }
  html, body { width: 1024px; height: 500px; overflow: hidden; }
  body {
    position: relative;
    background:
      radial-gradient(620px 420px at 96% 0%, ${GLOW}66, transparent 70%),
      radial-gradient(520px 380px at 4% 108%, ${EMBER}40, transparent 70%),
      ${GROUND};
    color: ${INK};
    font-family: ${FONT};
    -webkit-font-smoothing: antialiased;
  }
  /* The one loud thing: the logo's crescent, behind what it lights. */
  .moon { position: absolute; left: 470px; top: -60px; width: 620px; opacity: 0.5; filter: blur(0.5px); }
  .words { position: absolute; left: 64px; top: 0; width: 400px; height: 500px; display: flex; flex-direction: column; justify-content: center; }
  .brand { display: flex; align-items: center; gap: 12px; font-size: 22px; font-weight: 600; letter-spacing: -0.2px; }
  .brand svg { width: 34px; }
  h1 { margin-top: 28px; font-size: 50px; line-height: 1.04; font-weight: 650; letter-spacing: -1.6px; text-wrap: balance; }
  p { margin-top: 18px; max-width: 340px; font-size: 18px; line-height: 1.45; color: ${MUTED}; text-wrap: pretty; }
  .phone, .window { position: absolute; overflow: hidden; background: ${GROUND}; box-shadow: 0 30px 80px -20px #000c, 0 0 0 1px #ffffff1f; }
  .phone { width: 236px; border-radius: 38px; border: 5px solid #1b1922; }
  .phone img, .window img { display: block; width: 100%; }
  .window { border-radius: 14px; }
  .bar { display: flex; align-items: center; gap: 7px; height: 34px; padding: 0 14px; background: #17151d; border-bottom: 1px solid #ffffff14; }
  .bar i { width: 10px; height: 10px; border-radius: 50%; background: #ffffff2e; }
  .bar span { margin-left: 14px; padding: 4px 14px; border-radius: 8px; background: #ffffff12; color: ${MUTED}; font-size: 11px; }
</style></head><body>
  <div class="moon">${moon("b")}</div>
  ${graphic.stage}
  <div class="words">
    <div class="brand">${moon("a")}Penombre</div>
    <h1>${graphic.line}</h1>
    <p>${graphic.detail}</p>
  </div>
</body></html>`;

await mkdir(out, { recursive: true });
// PENOMBRE_CHROME: a Chromium to use when Playwright's own is not installed.
const browser = await chromium.launch({
	executablePath: process.env.PENOMBRE_CHROME || undefined,
});
for (const graphic of GRAPHICS) {
	// Twice the layout's size for the docs, where it is shown wide.
	const context = await browser.newContext({
		viewport: { width: 1024, height: 500 },
		deviceScaleFactor: 2,
	});
	const tab = await context.newPage();
	await tab.setContent(page(graphic), { waitUntil: "load" });
	const png = await tab.screenshot();
	await Bun.write(
		join(out, `${graphic.name}.webp`),
		await new Bun.Image(png).webp({ quality: 92 }).bytes(),
	);
	await context.close();
	process.stdout.write(`${graphic.name}.webp\n`);
}

// The Play Store's feature graphic: 1024x500 exactly, and no alpha channel.
const store = await browser.newContext({
	viewport: { width: 1024, height: 500 },
});
const listing = await store.newPage();
const mobile = GRAPHICS.find((graphic) => graphic.name === "feature-mobile");
if (mobile) {
	await listing.setContent(page(mobile), { waitUntil: "load" });
	const target = join(root, "mobile/store/feature-graphic.jpg");
	await mkdir(join(root, "mobile/store"), { recursive: true });
	await listing.screenshot({ path: target, type: "jpeg", quality: 95 });
	process.stdout.write("mobile/store/feature-graphic.jpg\n");
}

// The Play Store's phone screenshots. Play refuses a long side more than twice
// the short one, which the shots themselves are, so each stands in a 9:16 frame.
const screenshot = (shot: string, line: string) => `<!doctype html>
<html><head><meta charset="utf-8"><style>
  * { box-sizing: border-box; margin: 0; }
  html, body { width: 1080px; height: 1920px; overflow: hidden; }
  body {
    position: relative;
    background:
      radial-gradient(900px 700px at 100% 0%, ${GLOW}66, transparent 70%),
      radial-gradient(800px 600px at 0% 100%, ${EMBER}40, transparent 70%),
      ${GROUND};
    color: ${INK};
    font-family: ${FONT};
    -webkit-font-smoothing: antialiased;
  }
  .moon { position: absolute; left: 240px; top: 560px; width: 1100px; opacity: 0.5; }
  .brand { position: absolute; inset: 120px 0 auto; display: flex; justify-content: center; align-items: center; gap: 18px; font-size: 40px; font-weight: 600; }
  .brand svg { width: 60px; }
  h1 { position: absolute; inset: 210px 90px auto; text-align: center; font-size: 76px; line-height: 1.05; font-weight: 650; letter-spacing: -2px; text-wrap: balance; }
  .phone { position: absolute; left: 210px; top: 480px; width: 660px; overflow: hidden; border-radius: 96px; border: 12px solid #1b1922; background: ${GROUND}; box-shadow: 0 40px 120px -30px #000c, 0 0 0 2px #ffffff1f; }
  .phone img { display: block; width: 100%; }
</style></head><body>
  <div class="moon">${moon("b")}</div>
  <div class="brand">${moon("a")}Penombre</div>
  <h1>${line}</h1>
  <div class="phone"><img src="${shot}" alt=""></div>
</body></html>`;
const SCREENSHOTS = [
	{ shot: drive, line: "Your whole drive, in your pocket." },
	{ shot: player, line: "Music and video, from your own server." },
];
const phones = await browser.newContext({
	viewport: { width: 1080, height: 1920 },
});
const phoneTab = await phones.newPage();
for (const [index, { shot, line }] of SCREENSHOTS.entries()) {
	const name = `mobile/store/phone-${index + 1}.jpg`;
	await phoneTab.setContent(screenshot(shot, line), { waitUntil: "load" });
	await phoneTab.screenshot({
		path: join(root, name),
		type: "jpeg",
		quality: 92,
	});
	process.stdout.write(`${name}\n`);
}
await browser.close();
