[test]
preload = ["./packages/web/test.setup.ts"]
coverage = true
coveragePathIgnorePatterns = [
    "**/setup.ts",
    "**/test.setup.ts",
    "**/*.spec.ts",
    "**/test-utils.ts",
    "**/mocks/**",
    "**/types/**",
    "**/schema.ts",
    "**/*.test.ts",
    "**/*.spec.ts",
    "**/*.e2e.ts",
    "*.config.js",
    "*.config.ts",
    "webpack.config.*",
    "vite.config.*",
    "dist/**",
    "build/**",
    ".next/**",
    "generated/**",
    "**/*.generated.ts",
    "vendor/**",
    "third-party/**",
    "src/utils/constants.ts",
    "src/types/**",
]


[test.coverageThreshold]
line = 0.7
function = 0.8
statement = 0.9

[run]
bun = true

[install]
linker = "isolated"

[install.lockfile]
save = true

[runtime]
telemetry = false

[console]
depth = 3
