table account {
  id text [pk, not null]
  account_id text [not null]
  provider_id text [not null]
  user_id text [not null]
  access_token text
  refresh_token text
  id_token text
  access_token_expires_at integer
  refresh_token_expires_at integer
  scope text
  password text
  created_at integer [not null]
  updated_at integer [not null]

  indexes {
    user_id [name: 'account_userId_idx']
  }
}

table activity {
  id text [pk, not null]
  user_id text [not null]
  action text [not null]
  message text [not null]
  link text
  level text [not null]
  created_at integer [not null]

  indexes {
    user_id [name: 'activity_userId_idx']
    created_at [name: 'activity_createdAt_idx']
  }
}

table apikey {
  id text [pk, not null]
  config_id text [not null]
  name text
  start text
  prefix text
  key text [not null]
  reference_id text [not null]
  refill_interval integer
  refill_amount integer
  last_refill_at integer
  enabled integer [not null]
  rate_limit_enabled integer [not null]
  rate_limit_time_window integer
  rate_limit_max integer
  request_count integer [not null]
  remaining integer
  last_request integer
  expires_at integer
  created_at integer [not null]
  updated_at integer [not null]
  permissions text
  metadata text [default: `{}`]
}

table files {
  id text [pk, not null]
  name text [not null]
  owner_id text [not null]
  path text [not null]
  folder_id text
  content_type text [not null, default: 'application/octet-stream']
  category text [not null, default: 'UNKNOWN']
  size integer [not null, default: 0]
  is_trashed integer [not null, default: false]
  is_starred integer [not null, default: false]
  tags text [not null, default: `[]`]
  music_duration real
  video_duration real
  created_at integer [not null]
  updated_at integer [not null]

  indexes {
    owner_id [name: 'files_ownerId_idx']
    folder_id [name: 'files_folderId_idx']
    (path, owner_id) [name: 'files_path_ownerId_idx']
  }
}

table folders {
  id text [pk, not null]
  name text [not null]
  owner_id text [not null]
  path text [not null]
  parent_id text
  is_trashed integer [not null, default: false]
  is_starred integer [not null, default: false]
  tags text [not null, default: `[]`]
  created_at integer [not null]
  updated_at integer [not null]

  indexes {
    owner_id [name: 'folders_ownerId_idx']
    parent_id [name: 'folders_parentId_idx']
    (path, owner_id) [name: 'folders_path_ownerId_idx']
  }
}

table passkey {
  id text [pk, not null]
  name text
  public_key text [not null]
  user_id text [not null]
  credential_id text [not null]
  counter integer [not null]
  device_type text [not null]
  backed_up integer [not null]
  transports text
  created_at integer
  aaguid text
}

table session {
  id text [pk, not null]
  expires_at integer [not null]
  token text [not null, unique]
  created_at integer [not null]
  updated_at integer [not null]
  ip_address text
  user_agent text
  user_id text [not null]
  impersonated_by text

  indexes {
    user_id [name: 'session_userId_idx']
  }
}

table shared_with {
  id text [pk, not null]
  sharing_id text [not null]
  user_id text [not null]
  created_at integer [not null]

  indexes {
    sharing_id [name: 'sharedWith_sharingId_idx']
    user_id [name: 'sharedWith_userId_idx']
  }
}

table sharings {
  id text [pk, not null]
  owner_id text [not null]
  resource_type text [not null]
  resource_id text [not null]
  permission text [not null]
  created_at integer [not null]
  updated_at integer [not null]
  expiration integer

  indexes {
    owner_id [name: 'sharings_ownerId_idx']
    resource_id [name: 'sharings_resourceId_idx']
  }
}

table user {
  id text [pk, not null]
  name text [not null]
  email text [not null, unique]
  email_verified integer [not null, default: false]
  image text
  created_at integer [not null]
  updated_at integer [not null]
  role text
  banned integer [default: false]
  ban_reason text
  ban_expires integer
}

table user_preferences {
  user_id text [pk, not null]
  preferences text [default: `{}`]
  updated_at integer [not null]
}

table verification {
  id text [pk, not null]
  identifier text [not null]
  value text [not null]
  expires_at integer [not null]
  created_at integer [not null]
  updated_at integer [not null]

  indexes {
    identifier [name: 'verification_identifier_idx']
  }
}