table account {
  id text [pk, not null]
  account_id text [not null]
  provider_id text [not null]
  user_id text [not null]
  access_token text
  refresh_token text
  id_token text
  access_token_expires_at timestamp
  refresh_token_expires_at timestamp
  scope text
  password text
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null]

  indexes {
    user_id [name: 'account_userId_idx']
  }
}

table activity {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  user_id text [not null]
  action text [not null]
  message text [not null]
  link text
  level text [not null]
  created_at timestamp [not null]

  indexes {
    user_id [name: 'activity_userId_idx']
  }
}

table apikey {
  id text [pk, not null]
  config_id text [not null]
  name text
  start text
  prefix text
  key text [not null]
  reference_id text [not null]
  refill_interval integer
  refill_amount integer
  last_refill_at "timestamp (6) with time zone"
  enabled boolean [not null]
  rate_limit_enabled boolean [not null]
  rate_limit_time_window integer
  rate_limit_max integer
  request_count integer [not null]
  remaining integer
  last_request "timestamp (6) with time zone"
  expires_at "timestamp (6) with time zone"
  created_at "timestamp (6) with time zone" [not null]
  updated_at "timestamp (6) with time zone" [not null]
  permissions text
  metadata jsonb [default: `{}`]
}

table session {
  id text [pk, not null]
  expires_at timestamp [not null]
  token text [not null, unique]
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null]
  ip_address text
  user_agent text
  user_id text [not null]
  impersonated_by text

  indexes {
    user_id [name: 'session_userId_idx']
  }
}

table shared_with {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  sharing_id uuid [not null]
  user_id text [not null]
  created_at timestamp [not null]

  indexes {
    sharing_id [name: 'sharedWith_sharingId_idx']
    user_id [name: 'sharedWith_userId_idx']
  }
}

table sharings {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  owner_id text [not null]
  resource_type text [not null]
  resource_id text [not null]
  permission text [not null]
  created_at timestamp [not null]
  updated_at timestamp [not null]
  expiration timestamp

  indexes {
    owner_id [name: 'sharings_ownerId_idx']
  }
}

table user {
  id text [pk, not null]
  name text [not null]
  email text [not null, unique]
  email_verified boolean [not null, default: false]
  image text
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  role text
  banned boolean [default: false]
  ban_reason text
  ban_expires timestamp
}

table user_preferences {
  user_id text [pk, not null]
  preferences jsonb [default: `{}`]
  updated_at timestamp [not null, default: `now()`]
}

table verification {
  id text [pk, not null]
  identifier text [not null]
  value text [not null]
  expires_at timestamp [not null]
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]

  indexes {
    identifier [name: 'verification_identifier_idx']
  }
}

ref: account.user_id > user.id

ref: activity.user_id > user.id

ref: session.user_id > user.id

ref: shared_with.sharing_id > sharings.id

ref: shared_with.user_id > user.id

ref: sharings.owner_id > user.id

ref: user_preferences.user_id - user.id