server {
    listen 8080;
    listen [::]:8080;
    root /usr/share/nginx/html;
    
    server_name _;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    gzip_static on;

    include /etc/nginx/mime.types;

    error_page 404 /error.html; 

    location = /error.html {
        internal;
    }
}
