import type { FileCategory, FileContentType } from "$lib/server/schema";

export function determineContentType(key: string): FileContentType {
	const extension = key.split(".").pop()?.toLowerCase();
	switch (extension) {
		// Images
		case "jpg":
		case "jpeg":
			return "image/jpeg";
		case "png":
			return "image/png";
		case "gif":
			return "image/gif";
		case "webp":
			return "image/webp";
		case "svg":
			return "image/svg+xml";
		case "bmp":
			return "image/bmp";
		case "ico":
			return "image/x-icon";
		case "tiff":
		case "tif":
			return "image/tiff";
		case "heic":
		case "heif":
			return "image/heic";
		// Video
		case "mp4":
		case "m4v":
			return "video/mp4";
		case "webm":
			return "video/webm";
		case "avi":
			return "video/x-msvideo";
		case "mkv":
			return "video/x-matroska";
		case "mov":
			return "video/quicktime";
		case "wmv":
			return "video/x-ms-wmv";
		case "flv":
			return "video/x-flv";
		case "mpeg":
		case "mpg":
			return "video/mpeg";
		case "3gp":
			return "video/3gpp";
		case "ogv":
			return "video/ogg";
		// Audio
		case "mp3":
			return "audio/mpeg";
		case "wav":
			return "audio/wav";
		case "flac":
			return "audio/flac";
		case "aac":
			return "audio/aac";
		case "ogg":
		case "opus":
			return "audio/ogg";
		case "m4a":
			return "audio/mp4";
		case "wma":
			return "audio/x-ms-wma";
		case "aiff":
			return "audio/aiff";
		// Documents
		case "pdf":
			return "application/pdf";
		case "doc":
			return "application/msword";
		case "docx":
			return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
		case "xls":
			return "application/vnd.ms-excel";
		case "xlsx":
			return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
		case "ppt":
			return "application/vnd.ms-powerpoint";
		case "pptx":
			return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
		case "odt":
			return "application/vnd.oasis.opendocument.text";
		case "rtf":
			return "application/rtf";
		case "csv":
			return "text/csv";
		case "epub":
			return "application/epub+zip";
		// Google Suite
		case "gdoc":
			return "application/vnd.google-apps.document";
		case "gsheet":
			return "application/vnd.google-apps.spreadsheet";
		case "gslide":
			return "application/vnd.google-apps.presentation";
		// Text/Code
		case "txt":
		case "md":
			return "text/plain";
		case "html":
		case "htm":
			return "text/html";
		case "css":
			return "text/css";
		case "js":
		case "mjs":
			return "application/javascript";
		case "json":
			return "application/json";
		case "xml":
			return "application/xml";
		case "yaml":
		case "yml":
			return "text/yaml";
		// Archives
		case "zip":
			return "application/zip";
		case "rar":
			return "application/vnd.rar";
		case "7z":
			return "application/x-7z-compressed";
		case "tar":
			return "application/x-tar";
		case "gz":
			return "application/gzip";
		default:
			return "application/octet-stream";
	}
}

export function determineCategory(key: string): FileCategory {
	const extension = key.split(".").pop()?.toLowerCase();
	switch (extension) {
		// Music
		case "mp3":
		case "wav":
		case "flac":
		case "aac":
		case "ogg":
		case "wma":
		case "m4a":
		case "aiff":
		case "alac":
		case "opus":
			return "MUSIC";
		// Documents
		case "pdf":
		case "doc":
		case "docx":
		case "txt":
		case "rtf":
		case "odt":
		case "xls":
		case "xlsx":
		case "ppt":
		case "pptx":
		case "csv":
		case "md":
		case "epub":
		case "pages":
		case "numbers":
		case "keynote":
		case "gdoc":
		case "gsheet":
		case "gslide":
			return "DOCUMENTS";
		// Images
		case "jpg":
		case "jpeg":
		case "png":
		case "gif":
		case "svg":
		case "webp":
		case "bmp":
		case "ico":
		case "tiff":
		case "tif":
		case "heic":
		case "heif":
		case "raw":
		case "cr2":
		case "nef":
		case "arw":
		case "dng":
		case "psd":
		case "ai":
		case "eps":
			return "IMAGES";
		// Video
		case "mp4":
		case "avi":
		case "mkv":
		case "mov":
		case "wmv":
		case "flv":
		case "webm":
		case "m4v":
		case "mpeg":
		case "mpg":
		case "3gp":
		case "ogv":
		case "ts":
		case "mts":
		case "m2ts":
		case "vob":
			return "VIDEO";
		// Code
		case "js":
		case "py":
		case "java":
		case "c":
		case "cpp":
		case "h":
		case "hpp":
		case "cs":
		case "go":
		case "rs":
		case "rb":
		case "php":
		case "swift":
		case "kt":
		case "scala":
		case "sh":
		case "bash":
		case "zsh":
		case "ps1":
		case "sql":
		case "html":
		case "css":
		case "scss":
		case "sass":
		case "less":
		case "json":
		case "xml":
		case "yaml":
		case "yml":
		case "toml":
		case "ini":
		case "cfg":
		case "conf":
		case "env":
		case "dockerfile":
		case "makefile":
		case "cmake":
		case "gradle":
		case "jsx":
		case "tsx":
		case "vue":
		case "svelte":
		case "astro":
		case "lua":
		case "r":
		case "m":
		case "mm":
		case "pl":
		case "pm":
		case "ex":
		case "exs":
		case "erl":
		case "hrl":
		case "hs":
		case "elm":
		case "clj":
		case "cljs":
		case "lisp":
		case "scm":
		case "rkt":
		case "asm":
		case "s":
		case "v":
		case "sv":
		case "vhd":
		case "vhdl":
			return "CODE";
		default:
			return "UNKNOWN";
	}
}
