name: Check

on:
  workflow_call:
  push:

env:
  PNPM_VERSION: 10.11.0
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/opendrive
  OAUTH_CLIENT_ID: 123
  OAUTH_CLIENT_SECRET: acb456
  BETTER_AUTH_SECRET: very_secret_secret
  BETTER_AUTH_URL: http://localhost:5173

jobs:
  node:
    name: 'Node'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Verify Formatting
        run: bun run format:check

      - name: Lint
        run: bun run lint

      - name: Look for circular dependencies
        run: bun run circular

      - name: Run TypeScript check
        run: bun run check

      - name: Build the app
        run: bun run build
