name: CI

on:
  workflow_call:
  pull_request:

permissions: read-all

env:
  PNPM_VERSION: 10.12.4
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@service-db:5432/opendrive
  MINIO_URL: http://minio:9000
  NODE_VERSION: 22
  AWS_ACCESS_KEY_ID: opendrive
  AWS_SECRET_ACCESS_KEY: opendrive

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Test with Race Detector
        run: go test -v -race ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - name: Validate Compose configurations
        shell: bash
        run: |
          docker compose -f compose.yaml config --quiet
          docker compose -f compose.local.yaml config --quiet
          docker compose -f compose.prod.yaml config --quiet

      - name: Build
        shell: bash
        run: docker buildx bake

  node:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [circular, check, build, 'lint', 'format:check']
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts --prefer-offline

      - name: Sync routes
        run: pnpm exec kit-routes sync

      - name: Run '${{ matrix.job }}' command 🧪
        run: pnpm ${{ matrix.job }}
