name: CI

on:
  workflow_call:
  push:
    branches-ignore:
      - main

env:
  PNPM_VERSION: 10.11.0
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@service-db:5432/opendrive
  MINIO_URL: http://service-s3:9000
  OAUTH_CLIENT_ID: 123
  OAUTH_CLIENT_SECRET: acb456
  BETTER_AUTH_SECRET: very_secret_secret
  BETTER_AUTH_URL: http://0.0.0.0:5173
  NODE_VERSION: 22

jobs:
  checks:
    name: 'Checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Verify Formatting
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Look for circular dependencies
        run: pnpm run circular

      - name: Run TypeScript check
        run: pnpm run check

      - name: Build the app
        run: pnpm run build

  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      service-db:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: opendrive
        ports:
          - 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd "pg_isready -U ${POSTGRES_USER-postgres} -d ${POSTGRES_DB-opendrive}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      service-s3:
        # Docker Hub image
        image: lazybit/minio
        # Provide the password for postgres
        env:
          MINIO_ROOT_USER: opendrive
          MINIO_ROOT_PASSWORD: opendrive
        volumes:
          - minio_data:/data
        ports:
          - 9000
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd "curl -f http://0.0.0.0:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Sync
        run: pnpm exec svelte-kit sync

      - name: DB Migration
        run: pnpm run db:migrate

      - name: Run tests
        run: pnpm run test:ci

  docker-dry:
    name: 'Docker dry run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compose Build
        shell: bash
        run: docker compose -f compose.local.yaml build

      - name: Compose Pull
        shell: bash
        run: docker compose -f compose.local.yaml pull

      - name: Compose Dry Run
        shell: bash
        run: docker compose -f compose.local.yaml up -d --wait --remove-orphans --dry-run

      - name: Compose cleanup
        shell: bash
        run: docker compose -f compose.local.yaml down -v
