name: PR Docker Validation

on:
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/docker.yaml"
      - "docker-bake.hcl"
      - ".dockerignore"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  TZ: Europe/Paris
  REGISTRY_IMAGE: orochibraru/penombre
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  docker-prepare:
    uses: ./.github/workflows/docker.yaml
    name: Docker Prepare
    with:
      publish: false
      image-name: orochibraru/penombre
