name: Verify / Docker

on:
  workflow_call:
  pull_request:

permissions:
  contents: read
  pull-requests: write # To post comments

env:
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@db:5432/opendrive?sslmode=disable
  STORAGE_URL: http://minio:9000
  STORAGE_ACCESS_KEY_ID: opendrive
  STORAGE_ACCESS_KEY_SECRET: opendrive
  OAUTH_PROVIDERS: "pocketid"
  OAUTH_POCKETID_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_POCKETID_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  OAUTH_POCKETID_DISCOVERY_URL: https://auth.ombrage.space/.well-known/openid-configuration
  OAUTH_POCKETID_REDIRECT_URL: https://pr-${{ github.event.number }}-drive.ombrage.space/api/v1/auth/oauth/pocketid/callback

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - uses: actions/checkout@v4

      - name: Validate Compose configurations
        shell: bash
        run: |
          docker compose -f compose.yaml config --quiet
