name: Verify / Docker

on:
  workflow_call:
  pull_request:

permissions:
  contents: read
  pull-requests: write # To post comments

env:
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@db:5432/opendrive?sslmode=disable
  OAUTH_PROVIDERS: "pocketid"
  OAUTH_POCKETID_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_POCKETID_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  OAUTH_POCKETID_DISCOVERY_URL: https://auth.ombrage.space/.well-known/openid-configuration
  OAUTH_POCKETID_REDIRECT_URL: https://pr-${{ github.event.number }}-drive.ombrage.space/auth/oauth/pocketid/callback

jobs:
  docker-mr:
    runs-on: ubuntu-latest
    name: Docker build & Push
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v5

      - name: Build
        shell: bash
        run: docker buildx bake --file ./docker-bake.hcl app
