name: Verify / Go

on:
  workflow_call:
  pull_request:
    paths:
      - "packages/api/**"
      - ".github/workflows/go.yaml"

permissions:
  contents: read
  pull-requests: write # To post comments

env:
  TZ: Europe/Paris
  DATABASE_URL: postgres://postgres:postgres@db:5432/opendrive?sslmode=disable
  STORAGE_URL: http://minio:9000
  STORAGE_ACCESS_KEY_ID: opendrive
  STORAGE_ACCESS_KEY_SECRET: opendrive
  OAUTH_PROVIDERS: "pocketid"
  OAUTH_POCKETID_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_POCKETID_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  OAUTH_POCKETID_DISCOVERY_URL: https://auth.ombrage.space/.well-known/openid-configuration
  OAUTH_POCKETID_REDIRECT_URL: https://pr-${{ github.event.number }}-drive.ombrage.space/api/v1/auth/oauth/pocketid/callback
  GO_VERSION: 1.25.2
  GOLANGCI_LINT_VERSION: v2.5.0

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packages/api
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test with Race Detector
        run: go test -v -race ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: packages/api
