name: Publish
on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-publish
  cancel-in-progress: false

env:
  TZ: Europe/Paris

jobs:
  # ===========================================
  # Docker: Build (PR) or Build & Push (main)
  # ===========================================
  docker:
    name: Docker
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
      IMAGE: penombre/penombre
    if: github.event_name != 'pull_request' || !startsWith(github.event.pull_request.title, 'WIP')
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v6

      # Only login and push on main branch
      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: orochibraru
          password: ${{ secrets.CI_TOKEN }}

      # Main: Build and push
      - name: Build and push
        shell: bash
        run: docker buildx bake --file ./docker-bake.hcl --push
