name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*.*.*"
    paths-ignore:
      - ".husky/**"
      - "packages/docs/**"
      - "**/*.md"

concurrency:
  group: release
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: write

env:
  TZ: Europe/Paris
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check:
    uses: ./.github/workflows/ci.yaml
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    needs: [check]
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          # User
          git config --global user.name "Release Bot"
          git config --global user.email "no-reply@ombrage.space"
          # Credentials
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.CI_TOKEN }}@github.com" > ~/.git-credentials

      - name: Semantic Release
        id: semantic # We need this ID to grab the version output in the next steps
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
