name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - ".husky/**"

concurrency:
  group: release
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: write

env:
  TZ: Europe/Paris
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check:
    uses: ./.github/workflows/pr.yaml
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    needs: [check]
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          # User
          git config --global user.name "Release Bot"
          git config --global user.email "no-reply@ombrage.space"
          # Credentials
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.CI_TOKEN }}@github.com" > ~/.git-credentials

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Create a release commit
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog [skip ci]"
          git push origin HEAD:main
