/**
 * Produces the screenshots used by the README and the docs site.
 *
 * Not a test of behaviour — it asserts only enough to fail loudly when a page
 * stops rendering, so a broken screen can't be published as marketing. Run it
 * on demand:
 *
 *     bun run screenshots
 *
 * Output lands in `docs/images/`, which both the README and `packages/docs`
 * reference directly.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";
import { expect, test } from "@playwright/test";
import { AUTH_STORAGE_STATE, goToBrowse, openUploadDialog } from "../helpers";

const OUT_DIR = join(process.cwd(), "docs", "images");

/** Wide enough to show the sidebar and a full grid row. */
test.use({
	storageState: AUTH_STORAGE_STATE,
	viewport: { width: 1440, height: 900 },
});

// Screenshots are a serial pipeline over one seeded library, not independent
// cases — running them in parallel would race on the same uploads.
test.describe.configure({ mode: "serial" });

test.beforeAll(async () => {
	await mkdir(OUT_DIR, { recursive: true });
});

/**
 * Seed a handful of files so the shots show a populated app rather than an
 * empty state. Uses the fixtures already committed for the other suites.
 */
test("seeds sample media", async ({ page }) => {
	await goToBrowse(page);
	await openUploadDialog(page);

	const dialog = page.getByRole("dialog");
	await expect(dialog).toBeVisible();

	await dialog
		.locator("input[type=file]")
		.first()
		.setInputFiles(
			["test-image.png", "test-upload.txt"].map((name) =>
				join(process.cwd(), "e2e", "fixtures", name),
			),
		);
	await dialog.getByRole("button", { name: /upload/i }).click();

	await expect(page.getByText("test-image.png").first()).toBeVisible({
		timeout: 20_000,
	});
});

const SHOTS: Array<{ name: string; path: string; expect: RegExp }> = [
	{ name: "browse", path: "/browse", expect: /my drive/i },
	{ name: "shared", path: "/shared", expect: /shared/i },
	{ name: "settings-appearance", path: "/settings/display", expect: /theme/i },
	{ name: "settings-storage", path: "/settings/storage", expect: /storage/i },
	{ name: "admin", path: "/admin", expect: /dashboard/i },
	{
		name: "admin-activity",
		path: "/admin/activity",
		expect: /admin/i,
	},
];

for (const shot of SHOTS) {
	for (const theme of ["light", "dark"] as const) {
		test(`captures ${shot.name} (${theme})`, async ({ page }) => {
			await page.emulateMedia({ colorScheme: theme });
			await page.goto(shot.path);
			await page.waitForLoadState("networkidle");

			// Fail rather than publish a redirected, blank or errored page.
			// The URL check catches an auth redirect, which would otherwise
			// publish the drive under an "admin" filename.
			expect(new URL(page.url()).pathname).toBe(shot.path);
			await expect(page.getByText(shot.expect).first()).toBeVisible({
				timeout: 15_000,
			});

			// Let the aurora and any thumbnails settle so shots are stable.
			await page.waitForTimeout(1200);

			const suffix = theme === "dark" ? "-dark" : "";
			await page.screenshot({
				path: join(OUT_DIR, `${shot.name}${suffix}.png`),
				fullPage: false,
			});
		});
	}
}

test("writes an index of what was captured", async () => {
	const lines = SHOTS.flatMap((shot) =>
		["", "-dark"].map(
			(suffix) => `- \`${shot.name}${suffix}.png\` — ${shot.path}`,
		),
	);
	await writeFile(
		join(OUT_DIR, "README.md"),
		[
			"# Screenshots",
			"",
			"Generated by `bun run screenshots`. Do not edit by hand.",
			"",
			...lines,
			"",
		].join("\n"),
	);
});
